layout: {qmk_keyboard: fingerpunch/ximi/v2, layout_name: LAYOUT_5col}
layers:
  Colemak:
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - - {type: 'encoder'}
      - "BOOT MAGIC"
      -
      -
      -
      -
      - "BOOT MAGIC"
    - - {type: 'encoder'}
      -
      -
    - ['', '', '', '']
  Accents:
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - - {type: 'encoder'}
      -
      -
      -
      -
      -
      -
    - - {type: 'encoder'}
      -
      -
    - ['', '', '', '']
  Symbols:
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - - {type: 'encoder'}
      -
      -
      -
      -
      -
      -
    - - {type: 'encoder'}
      -
      -
    - ['', '', '', '']
  Navigation:
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - - {type: 'encoder'}
      -
      -
      -
      -
      -
      -
    - - {type: 'encoder'}
      -
      -
    - ['', '', '', '']
  Numbers:
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - - {type: 'encoder'}
      -
      -
      -
      -
      -
      -
    - - {type: 'encoder'}
      -
      -
    - ['', '', '', '']
  Mouse:
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - - {type: 'encoder'}
      -
      -
      -
      -
      -
      -
    - - {type: 'encoder'}
      -
      -
    - ['', '', '', '']
  Game:
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - ['', '', '', '', '', '', '', '', '', '']
    - - {type: 'encoder'}
      -
      -
      -
      -
      -
      -
    - - {type: 'encoder'}
      -
      -
    - ['', '', '', '']
