AUDIO_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
ENCODER_ENABLE = yes
HAPTIC_FEEDBACK = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
RGB_MATRIX_ENABLE = no
SEND_STRING_ENABLE = yes

FP_HAPTIC_MOUSE_BUTTONS = yes
FP_TRACKBALL_BOTH = yes
