#ifdef FP_ENCODER_ENABLE
// clang-format off
// Left Encoder
#define FP_ENC_0_LAYER_DPI_POINTING   0
#define FP_ENC_0_LAYER_SCROLL_WHEEL   1
#define FP_ENC_0_LAYER_ZOOM           2
#define FP_ENC_0_LAYER_PGUP_PGDN      3
#define FP_ENC_0_LAYER_VOLUME         4
#define FP_ENC_0_LAYER_RGB_MODE       5
#define FP_ENC_0_LAYER_RGB_SAT        6
#define FP_ENC_0_LAYER_RGB_VAL        7
#define FP_ENC_0_LAYER_RGB_HUE        8
#define FP_ENC_0_LAYER_SUPER_TAB      9
#define FP_ENC_0_LAYER_SUPER_CTRL_TAB 10

// Right Encoder
#define FP_ENC_1_LAYER_VOLUME         0
#define FP_ENC_1_LAYER_RGB_VAL        1
#define FP_ENC_1_LAYER_PGUP_PGDN      2
#define FP_ENC_1_LAYER_ZOOM           3
#define FP_ENC_1_LAYER_DPI_POINTING   4
#define FP_ENC_1_LAYER_SCROLL_WHEEL   5
#define FP_ENC_1_LAYER_RGB_HUE        6
#define FP_ENC_1_LAYER_RGB_MODE       7
#define FP_ENC_1_LAYER_RGB_SAT        8
#define FP_ENC_1_LAYER_SUPER_TAB      9
#define FP_ENC_1_LAYER_SUPER_CTRL_TAB 10
// clang-format on
#endif // FP_ENCODER_ENABLE
