SRC += jeffdess.c \
	features/achordion.c \
	haptic_feedback.c

ALLOW_WARNINGS = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
CONSOLE_ENABLE = yes
ENCODER_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
SEND_STRING_ENABLE = yes
INTROSPECTION_KEYMAP_C = combos.c
HAPTIC_ENABLE = yes
SPLIT_HAPTIC_ENABLE = yes
SPLIT_ACTIVITY_ENABLE = yes
